---
abstract: 'module to align text.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::More: '0'
  constant: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Aligner
provides:
  Text::Aligner:
    file: lib/Text/Aligner.pm
    version: '0.11'
  Text::Aligner::Auto:
    file: lib/Text/Aligner.pm
    version: '0.11'
  Text::Aligner::MaxKeeper:
    file: lib/Text/Aligner.pm
    version: '0.11'
requires:
  Exporter: '0'
  Term::ANSIColor: '2.02'
  perl: '5.008'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-Aligner
  repository: https://github.com/shlomif/Text-Aligner.git
version: '0.11'
