---
abstract: 'Align text in columns'
author:
  - 'Anno Siegel (siegel@zrz.tu-berlin.de)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Aligner
no_index:
  directory:
    - t
    - inc
requires:
  Term::ANSIColor: 2.01
  Test::More: 0
version: 0.08
